import { useMemo, useState } from 'react';
import { ArrowUpRight, Check, ChevronRight, CircleDot, Filter, Gem, Search, SlidersHorizontal, X } from 'lucide-react';
import { useGetCatalogueSummary, useListProducts, type Product } from '@workspace/api-client-react';
import { EmptyState, ErrorState, LoadingState } from '@/components/states';

function ProductArtwork({ product, large = false }: { product: Product; large?: boolean }) {
  if (product.imageUrl) return <img src={product.imageUrl} alt={product.name} className={`size-full object-cover transition-transform duration-500 group-hover:scale-[1.03] ${large ? 'max-h-[540px]' : ''}`} />;
  return <div className={`relative flex size-full items-center justify-center overflow-hidden bg-[#ece2d0] ${large ? 'min-h-[360px]' : 'min-h-[190px]'}`}><div className="absolute inset-0 opacity-60" style={{ background: 'radial-gradient(circle at 50% 45%, rgba(255,255,255,.85), transparent 32%), linear-gradient(135deg, transparent 40%, rgba(111,57,65,.08) 40%, transparent 62%)' }} /><div className="relative grid size-20 place-items-center rounded-full border border-[#bda67d]/50 text-[#8f6c38]"><Gem className={large ? 'size-9' : 'size-7'} strokeWidth={1} /></div><span className="absolute bottom-4 left-5 font-mono-ui text-[9px] uppercase tracking-[.2em] text-[#876f4d]">{product.material}</span></div>;
}

function ProductCard({ product, selected, onSelect }: { product: Product; selected: boolean; onSelect: () => void }) {
  return <button type="button" onClick={onSelect} data-testid={`card-product-${product.id}`} className={`group w-full overflow-hidden rounded-2xl border text-left transition-all duration-300 ${selected ? 'border-primary bg-card shadow-md shadow-primary/10' : 'border-border bg-card hover:-translate-y-1 hover:border-primary/40 hover:shadow-md'}`}>
    <div className="relative overflow-hidden"><ProductArtwork product={product} /><span className="absolute left-4 top-4 rounded-full bg-[#f8f1e7]/90 px-2.5 py-1 font-mono-ui text-[9px] uppercase tracking-widest text-[#765a37]">{product.category}</span><span className={`absolute right-4 top-4 size-2 rounded-full ${product.isPublished === false ? 'bg-[#ae7a63]' : 'bg-emerald-700'}`} title={product.isPublished === false ? 'Unpublished' : 'Published'} /></div>
    <div className="p-5"><p className="font-mono-ui text-[10px] tracking-[.16em] text-muted-foreground">{product.sku}</p><h3 className="mt-2 font-display text-[22px] leading-tight text-foreground">{product.name}</h3><div className="mt-4 flex items-center justify-between gap-4 text-xs text-muted-foreground"><span>{product.material}</span><span className="flex items-center gap-1 text-primary">View <ChevronRight className="size-3" /></span></div></div>
  </button>;
}

export default function CataloguePage() {
  const productsQuery = useListProducts();
  const summaryQuery = useGetCatalogueSummary();
  const products = productsQuery.data ?? [];
  const summary = summaryQuery.data;
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState('All pieces');
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [filtersOpen, setFiltersOpen] = useState(false);

  const categories = useMemo(() => ['All pieces', ...(summary?.categories ?? Array.from(new Set(products.map((product) => product.category))))], [products, summary?.categories]);
  const filteredProducts = useMemo(() => products.filter((product) => {
    const haystack = `${product.name} ${product.sku} ${product.material} ${product.vendorName}`.toLowerCase();
    return (category === 'All pieces' || product.category === category) && haystack.includes(search.toLowerCase());
  }), [category, products, search]);
  const selected = filteredProducts.find((product) => product.id === selectedId) ?? filteredProducts[0];

  return <div className="animate-in fade-in duration-500" data-testid="page-catalogue">
    <div className="mb-9 flex flex-col justify-between gap-6 border-b border-border/70 pb-8 xl:flex-row xl:items-end"><div><p className="eyebrow mb-4 text-primary">Curated collection · 01</p><h1 className="font-display text-5xl leading-none tracking-[-0.045em] text-foreground md:text-6xl">The catalogue<span className="text-primary">.</span></h1><p className="mt-4 max-w-xl text-sm leading-6 text-muted-foreground">A private edit of fine pieces from our partner ateliers. Select a piece to view its details and provenance.</p></div><div className="flex items-end gap-8"><div><p className="eyebrow text-muted-foreground">Available pieces</p><p className="mt-2 font-display text-3xl" data-testid="text-catalogue-product-count">{summary?.productCount ?? products.length}</p></div><div><p className="eyebrow text-muted-foreground">Ateliers</p><p className="mt-2 font-display text-3xl" data-testid="text-catalogue-vendor-count">{summary?.vendorCount ?? '—'}</p></div></div></div>
    <div className="mb-7 flex flex-col gap-3 lg:flex-row lg:items-center">
      <div className="relative flex-1"><Search className="pointer-events-none absolute left-4 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by name, SKU, material or atelier" data-testid="input-catalogue-search" className="h-12 w-full rounded-xl border border-input bg-card pl-11 pr-10 text-sm outline-none transition-shadow placeholder:text-muted-foreground/65 focus:border-primary focus:ring-4 focus:ring-primary/10" />{search && <button type="button" onClick={() => setSearch('')} aria-label="Clear search" data-testid="button-clear-search" className="absolute right-3 top-1/2 -translate-y-1/2 rounded-md p-1 text-muted-foreground hover:text-foreground"><X className="size-4" /></button>}</div>
      <div className="flex gap-2"><button type="button" onClick={() => setFiltersOpen((open) => !open)} data-testid="button-toggle-filters" className={`flex h-12 items-center gap-2 rounded-xl border px-4 text-xs font-bold transition-colors ${filtersOpen ? 'border-primary bg-primary text-primary-foreground' : 'border-input bg-card hover:border-primary/40'}`}><SlidersHorizontal className="size-4" />Filters</button><button type="button" onClick={() => { setSearch(''); setCategory('All pieces'); }} data-testid="button-reset-filters" className="hidden h-12 items-center gap-2 rounded-xl border border-input bg-card px-4 text-xs font-bold transition-colors hover:border-primary/40 sm:flex"><Filter className="size-3.5" />Reset</button></div>
    </div>
    {filtersOpen && <div className="mb-7 flex flex-wrap items-center gap-2 rounded-xl border border-border bg-card px-4 py-3 animate-in fade-in slide-in-from-top-1 duration-200" data-testid="panel-filters"><span className="eyebrow mr-2 text-muted-foreground">Category</span>{categories.map((item) => <button key={item} type="button" onClick={() => setCategory(item)} data-testid={`button-category-${item.toLowerCase().replaceAll(' ', '-')}`} className={`rounded-full px-3 py-1.5 text-xs transition-colors ${category === item ? 'bg-primary text-primary-foreground' : 'bg-secondary text-muted-foreground hover:text-foreground'}`}>{item}</button>)}</div>}
    {!filtersOpen && <div className="mb-7 flex gap-2 overflow-x-auto pb-1">{categories.slice(0, 6).map((item) => <button key={item} type="button" onClick={() => setCategory(item)} data-testid={`button-quick-category-${item.toLowerCase().replaceAll(' ', '-')}`} className={`shrink-0 rounded-full border px-3.5 py-2 text-xs transition-colors ${category === item ? 'border-primary bg-primary text-primary-foreground' : 'border-border bg-card text-muted-foreground hover:border-primary/40 hover:text-foreground'}`}>{item}</button>)}</div>}
    {productsQuery.isLoading ? <LoadingState /> : productsQuery.isError ? <ErrorState onRetry={() => productsQuery.refetch()} /> : filteredProducts.length === 0 ? <EmptyState searchTerm={search || category !== 'All pieces' ? search : undefined} /> :
      <div className="grid gap-7 xl:grid-cols-[minmax(0,1fr)_minmax(340px,0.72fr)]">
        <div><div className="mb-4 flex items-center justify-between"><p className="text-xs text-muted-foreground"><span className="font-semibold text-foreground">{filteredProducts.length}</span> pieces in view</p><p className="eyebrow text-muted-foreground">Select for detail</p></div><div className="grid gap-5 sm:grid-cols-2">{filteredProducts.map((product) => <ProductCard key={product.id} product={product} selected={selected?.id === product.id} onSelect={() => setSelectedId(product.id)} />)}</div></div>
        {selected && <aside className="h-fit overflow-hidden rounded-2xl border border-border bg-card xl:sticky xl:top-8" data-testid={`panel-product-detail-${selected.id}`}><div className="relative"><ProductArtwork product={selected} large /><div className="absolute bottom-4 left-5 flex items-center gap-2 rounded-full bg-[#f8f1e7]/90 px-3 py-1.5 text-[10px] font-bold uppercase tracking-widest text-[#765a37]"><CircleDot className="size-3" /> {selected.isPublished === false ? 'Private draft' : 'Available to view'}</div></div><div className="p-6 md:p-7"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow text-primary">{selected.category}</p><h2 className="mt-3 font-display text-4xl leading-none tracking-[-0.035em]">{selected.name}</h2></div><span className="font-mono-ui text-[10px] tracking-widest text-muted-foreground">{selected.sku}</span></div><div className="my-7 grid grid-cols-2 gap-4 border-y border-border py-5"><div><p className="eyebrow text-muted-foreground">Material</p><p className="mt-2 text-sm font-semibold">{selected.material}</p></div><div><p className="eyebrow text-muted-foreground">Atelier</p><p className="mt-2 text-sm font-semibold">{selected.vendorName}</p></div></div><p className="text-sm leading-7 text-muted-foreground">{selected.description || 'Details for this piece are available through your Aurum representative.'}</p><button type="button" onClick={() => window.alert('Please contact your Aurum representative to request availability.')} data-testid={`button-request-piece-${selected.id}`} className="mt-7 flex h-12 w-full items-center justify-center gap-2 rounded-lg bg-foreground text-sm font-bold text-background transition-all hover:-translate-y-0.5 hover:bg-primary">Request availability <ArrowUpRight className="size-4" /></button><div className="mt-4 flex items-center gap-2 text-[10px] uppercase tracking-widest text-muted-foreground"><Check className="size-3.5 text-emerald-700" /> Trade pricing shared privately</div></div></aside>}
      </div>}
  </div>;
}