import { useMemo } from 'react';
import { ArrowUpRight, Check, Gem, Lock, Store, Tag } from 'lucide-react';
import { useGetCatalogueSummary, useListProducts } from '@workspace/api-client-react';
import { useAuth } from '@/lib/auth';
import { EmptyState, ErrorState, LoadingState } from '@/components/states';

export default function VendorPage() {
  const { user } = useAuth();
  const productsQuery = useListProducts();
  const summaryQuery = useGetCatalogueSummary();
  const products = productsQuery.data ?? [];
  const sampleProducts = useMemo(() => products.slice(0, 4), [products]);
  const vendorName = user?.user_metadata?.vendorName || user?.email?.split('@')[0] || 'Trade partner';

  return <div className="animate-in fade-in duration-500" data-testid="page-vendor">
    <div className="mb-9 flex flex-col justify-between gap-6 border-b border-border/70 pb-8 md:flex-row md:items-end"><div><p className="eyebrow mb-4 text-primary">Partner desk · 03</p><h1 className="font-display text-5xl leading-none tracking-[-0.045em]">Your workspace<span className="text-primary">.</span></h1><p className="mt-4 max-w-xl text-sm leading-6 text-muted-foreground">Welcome back, {vendorName}. Your partner access keeps the right pieces close at hand.</p></div><div className="flex items-center gap-2 text-xs text-muted-foreground"><span className="size-2 rounded-full bg-emerald-700" />Access verified</div></div>
    {productsQuery.isLoading || summaryQuery.isLoading ? <LoadingState label="Loading vendor workspace" /> : productsQuery.isError || summaryQuery.isError ? <ErrorState onRetry={() => { void productsQuery.refetch(); void summaryQuery.refetch(); }} /> :
      <><div className="mb-8 grid gap-4 md:grid-cols-[1.35fr_1fr_1fr]"><div className="relative overflow-hidden rounded-2xl bg-sidebar p-6 text-sidebar-foreground"><div className="absolute -right-8 -top-16 size-48 rounded-full border border-sidebar-primary/20" /><div className="relative"><p className="eyebrow text-sidebar-primary">Partner access</p><h2 className="mt-8 max-w-xs font-display text-3xl leading-tight">A private view, prepared for you.</h2><p className="mt-3 max-w-xs text-xs leading-5 text-sidebar-foreground/60">Browse the live edit and share exact SKUs with your buying team.</p><div className="mt-8 flex items-center gap-2 text-[10px] uppercase tracking-widest text-sidebar-foreground/50"><Lock className="size-3.5 text-sidebar-primary" /> Secure trade environment</div></div></div><WorkspaceMetric icon={Gem} label="Pieces available" value={summaryQuery.data?.productCount ?? products.length} /><WorkspaceMetric icon={Store} label="Atelier partners" value={summaryQuery.data?.vendorCount ?? '—'} /></div>
      <div className="grid gap-7 lg:grid-cols-[minmax(0,1fr)_300px]"><section className="rounded-2xl border border-border bg-card"><div className="flex items-end justify-between border-b border-border p-5 md:p-6"><div><p className="eyebrow text-primary">Live selection</p><h2 className="mt-2 font-display text-2xl">Latest pieces</h2></div><span className="hidden items-center gap-1.5 text-xs text-muted-foreground sm:flex"><Check className="size-3.5 text-emerald-700" /> Published catalogue</span></div>{sampleProducts.length === 0 ? <div className="p-5"><EmptyState /></div> : <div className="divide-y divide-border">{sampleProducts.map((product) => <div key={product.id} className="group flex items-center gap-4 p-5 transition-colors hover:bg-secondary/35 md:px-6" data-testid={`row-vendor-product-${product.id}`}><div className="grid size-12 shrink-0 place-items-center rounded-xl bg-[#ece2d0] text-[#8f6c38]"><Gem className="size-5" strokeWidth={1.2} /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{product.name}</p><p className="mt-1 font-mono-ui text-[10px] uppercase tracking-widest text-muted-foreground">{product.sku} · {product.material}</p></div><span className="hidden text-xs text-muted-foreground sm:block">{product.vendorName}</span><button type="button" onClick={() => window.alert(product.description || 'Piece details are available through your Aurum representative.')} aria-label={`View ${product.name}`} data-testid={`button-view-vendor-product-${product.id}`} className="rounded-md p-2 text-muted-foreground transition-colors hover:bg-secondary hover:text-primary"><ArrowUpRight className="size-4" /></button></div>)}</div>}</section><aside className="h-fit space-y-5"><div className="rounded-2xl border border-border bg-card p-5"><p className="eyebrow text-primary">Your access</p><div className="mt-5 space-y-4"><AccessRow icon={Tag} label="Catalogue" value="Full published edit" /><AccessRow icon={Check} label="Account status" value="Verified partner" /><AccessRow icon={Store} label="Region" value="International" /></div></div><div className="rounded-2xl border border-[#cbb47c]/40 bg-[#f2e8d5] p-5 text-[#5e4a2f]"><p className="eyebrow text-[#8f6c38]">Working note</p><p className="mt-3 font-display text-xl leading-tight">Save the SKU.<br />We’ll handle the rest.</p><p className="mt-3 text-xs leading-5 text-[#806a49]">For availability or trade pricing, send an exact SKU to your Aurum representative.</p></div></aside></div></>}
  </div>;
}

function WorkspaceMetric({ icon: Icon, label, value }: { icon: typeof Gem; label: string; value: number | string }) {
  return <div className="rounded-2xl border border-border bg-card p-6"><Icon className="size-5 text-primary" strokeWidth={1.4} /><p className="eyebrow mt-8 text-muted-foreground">{label}</p><p className="mt-2 font-display text-4xl" data-testid={`text-vendor-${label.toLowerCase().replaceAll(' ', '-')}`}>{value}</p><p className="mt-1 text-xs text-muted-foreground">Current access</p></div>;
}

function AccessRow({ icon: Icon, label, value }: { icon: typeof Tag; label: string; value: string }) {
  return <div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-full bg-secondary text-primary"><Icon className="size-3.5" strokeWidth={1.7} /></span><span className="min-w-0 flex-1"><span className="block text-xs text-muted-foreground">{label}</span><span className="mt-0.5 block text-xs font-bold">{value}</span></span></div>;
}